Repository Nevatrip/frontend, pull requests merged in 2019-03, with the labels that each got.

#16 Feature/ci
  .dockerignore
  .env
  .git-crypt/.gitattributes
  .git-crypt/keys/default/0/66A343ADA887DCB609E85C05D67EEFE83EA18E1B.gpg
  .git-crypt/keys/default/0/A0368F1D9F50FB182CB950EC1A098860F5737A78.gpg
  .git-crypt/keys/default/0/DE1433349B517C978A1AE45E323B9165DB5BBBE2.gpg
  .gitattributes
  .gitignore
  .travis.yml
  Dockerfile
  README.md
  deploy.gpg.enc
  package-lock.json
Labels: enhancement

#23 Feature/#22 add docker build
  .docker/certbot/Dockerfile
  .docker/certbot/certs/.gitignore
  .docker/certbot/certs/.gitkeep
  .docker/certbot/letsencrypt/.gitkeep
  .docker/certbot/letsencrypt/.well-known/.gitkeep
  .docker/certbot/scripts/run-certbot.sh
  .docker/data/logs/nginx/access.log
  .docker/data/logs/nginx/error.log
  .docker/docker-compose.yml
  .docker/nginx/Dockerfile
  .docker/nginx/certs/.gitkeep
  .docker/nginx/nginx.conf
  .docker/nginx/scripts/build-nginx.sh
  .docker/nginx/scripts/run-openssl.sh
  .docker/nginx/sites/node-https.template
  .docker/nginx/sites/node.template
  .docker/node/Dockerfile
  .docker/node/scripts/run-nodock.sh
  .gitignore
  server/router.js
Labels: bug, enhancement

#25 Feature/#21 cart route queries
  bundles/cart.nevatrip-desktop/cart.nevatrip-desktop.bemdecl.js
  bundles/cart.nevatrip-desktop/cart.nevatrip-desktop.tmpl.bemdecl.js
  bundles/cart.nevatrip-touch/cart.nevatrip-touch.bemdecl.js
  bundles/cart.nevatrip-touch/cart.nevatrip-touch.tmpl.bemdecl.js
  components/common.blocks/cart/cart.bemtree.js
  components/common.blocks/cart/cart.deps.js
  components/common.blocks/cart/cart.js
  components/common.blocks/page/_route/page_route_cart.bemtree.js
  components/common.blocks/page/_route/page_route_cart.deps.js
  server/router.js
  server/routes/cart.js
Labels: bug
